'\" t
.\"     Title: ipset_list manual
.\"    Author: Mart Frauenlob aka AllKind <AllKind@fastest.cc>
.\" Generator: DocBook XSL-NS Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/30/2016
.\"    Manual: ipset_list 3.6
.\"    Source: ipset_list 3.6
.\"  Language: English
.\"
.TH "IPSET_LIST MANUAL" "8" "03/30/2016" "ipset_list 3.6" "ipset_list 3\&.6"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipset_list \- Match and display ipset (netfilter\&.org) sets in various ways
.SH "SYNOPSIS"
.HP \w'\fBipset_list\fR\ 'u
\fBipset_list\fR [\fIoption\fR\ [\ \fIoption_argument\fR\ ]...] [\fIset\-name\-glob\fR...]
.SH "FILES"
.PP

/usr/sbin/ipset_list
.PP

/etc/ipset_list/ipset_list\&.conf
.SH "DESCRIPTION"
.PP
ipset_list is a wrapper script for listing sets of the netfilter
\fBipset\fR
program\&. It allows you to match and display sets, headers, and elements in various ways\&. The resulting representation of the query can be saved in ipset `save\*(Aq and/or `xml\*(Aq format\&.
.PP
It is written for the
\fBbash\fR
shell\&.
.PP
It includes an interactive wizard based mode, that utilizes a dialog program (\fBdialog\fR
or
\fBwhiptail\fR
are supported)\&.
.PP
Optionally the output can be colorized\&.
.PP
A
\fIcompspec\fR
(programmable completion specification) for bash completion is included\&.
.PP
Some variables are available inside the script configuration header, or the configuration file (ipset_list\&.conf)\&. As the configuration file will be loaded after reading the configuration header, its settings take precedence\&. The variables are all undefined by default\&. Thus being available for manipulation in the environment at runtime\&. None of them is mandatory, unless you want to change default values\&. For details see section
\fBEnvironment\fR, or the comments inside
ipset_list[\&.conf]\&.
.PP
Some options exclude or require each other\&.
\fBipset_list\fR
will complain if that is the case\&. The output of
\fBipset_list \-h\fR
does display the valid combinations\&.
.PP
Example usage is given in the header of the script itself, or in the Readme\&.md shipping with
\fBipset_list\fR\&.
.SH "OPTIONS"
.PP
All options are optional\&. Some require an argument, others do not\&. All options and their arguments must be separated by
\fIblank\fR(s)\&. If an option can be used more than once, it is mentioned explicitly\&.
.PP
When run without arguments, the names of all sets found, are displayed with the prefix `Name:\*(Aq\&.
.PP
\-h, \-?
.RS 4
Show usage instructions\&.
.RE
.PP
\-v
.RS 4
Show version information\&.
.RE
.PP
\-
.RS 4
Enter interactive mode\&. This wizard based way to select the options utilizes a
\fIdialog\fR
program\&. Which can either be
\fBdialog\fR
or
\fBwhiptail\fR\&.
\fBdialog\fR
is the preferred and default, if the variable
\fIdialog_prog\fR
is not defined\&. Only dialog versions greater or equal to 1\&.2 are supported\&.
.RE
.PP
\-a
.RS 4
Show all information (header and members) but with default
\fIdelim\fR
(\fIwhitespace\fR)\&.
.RE
.PP
\-c
.RS 4
Calculate the total amout of set members and also the sum of members matching a criteria given by another option\&.
.RE
.PP
\-d delim
.RS 4
Delimiter character used to separate member entries\&. By default
\fBipset\fR
uses
\fInewline\fR
as delimiter\&.
\fBipset_list\fR
by default uses a
\fIwhitespace\fR\&. Which can be changed permanently by editing the variable
\fIdelim\fR
in the configuration header of ipset_list\&.
.sp
If this parameter is used when starting interactive mode, it will apply globally to all search queries performed\&. Unless you choose the
\fIDelim\fR
option from the menu, which will overwrite the global value just for that single query\&.
.RE
.PP
\-i
.RS 4
Show only the members of a
\fBsingle\fR
set\&.
.RE
.PP
\-m
.RS 4
Show the set(s) members\&.
.RE
.PP
\-n
.RS 4
Show the set names only\&. No prefix is shown, as when running
\fBipset_list\fR
without arguments\&.
.RE
.PP
\-r
.RS 4
Try to resolve ip addresses in the output (slow!)\&.
.sp
If this option is used when entering interactive mode, it will be pre\-selected in the menu, as long the session lasts\&.
.RE
.PP
\-s
.RS 4
Print elements sorted (if supported by the set type)\&.
.sp
If this option is used when entering interactive mode, it will be pre\-selected in the menu, as long the session lasts\&.
.RE
.PP
\-t
.RS 4
Show set headers
\fBonly\fR\&.
.RE
.PP
\-Ca
.RS 4
Enable all counters (shortcut for \-c \-Cs \-Ts \-Tm)\&.
.RE
.PP
\-Co
.RS 4
Colorize the output\&.
.sp
Requires the
\fBcl\fR
program\&. It can be downloaded from here:
\m[blue]\fBhttp://sf\&.net/projects/colorize\-shell/\fR\m[]
or:
\m[blue]\fBhttps://github\&.com/AllKind/cl\fR\m[]\&.
.sp
Configuration variables are available to adjust the color settings\&. Their names are prefixed with
col_*\&. The list of valid color names can be retrieved by running
\fBcl \-\-list\fR\&.
.sp
The default is not to use colored output\&. That can be changed by setting the
\fIcolorize\fR
variable to `1\*(Aq\&.
.sp
If this option is used when entering interactive mode, it will be pre\-selected in the menu, as long the session lasts\&.
.RE
.PP
\-Cs
.RS 4
Count the amount of sets that matched the search criteria\&.
.RE
.PP
\-Fg pattern
.RS 4
Match on members using a [ext]glob pattern\&.
.RE
.PP
\-Fr pattern
.RS 4
Match on members using a regex pattern\&.
.RE
.PP
\-Fh header\-glob:value\-glob [\&.\&.\&.]
.RS 4
Show sets containing one or more [ext]glob matching headers\&. This option can be used multiple times\&.
.RE
.PP
\-Fi header\-glob:[!|<|>|<=|>=]value [\&.\&.\&.]
.RS 4
Show sets matching one or more integer valued header entries\&. This option can be used multiple times\&.
.RE
.PP
\-G
.RS 4
When in interactive mode, generate the
\fBipset_list\fR
command\-line, as for use in \*(Aqnormal\*(Aq mode\&.
.sp
If this option is used when entering interactive mode, then the option will be pre\-selected in the menu, as long the session lasts\&.
.RE
.PP
\-Gp [a[uto]|n[one]file]
.RS 4
Save the result of the query as
\fBipset\fR
set creation commands\&. The format is equal to the output of `ipset save`\&.
.sp
If `\fIauto\fR\*(Aq is used as option argument, the file name is automatically generated\&. Otherwise it must be specified\&.
.sp
If `\fInone\fR\*(Aq is used as option argument, the output is sent to
\fIstdout\fR\&. This will suppress normal output\&.
.sp
The option argument can be omitted\&. In that case `\fIauto\fR\*(Aq is assumed\&.
.sp
The arguments `auto\*(Aq and `none\*(Aq can be written in short form\&. Meaning only the first character is mandatory\&.
.sp
It is not valid to use \-Gp none together with \-Gx none\&.
.sp
If this option is used when entering interactive mode, it will be pre\-selected in the menu, as long the session lasts\&.
.sp
The directory the file(s) will be saved into can be modified using the
\fIcachedir\fR
variable\&.
.RE
.PP
\-Gx [a[uto]|n[one]|file]
.RS 4
Save the result of the query as
\fBipset\fR
xml output\&. The format is equal to the output of `ipset save \-o xml`\&.
.sp
If `\fIauto\fR\*(Aq is used as option argument, the file name is automatically generated\&. Otherwise it must be specified\&.
.sp
If `\fInone\fR\*(Aq is used as option argument, the output is sent to
\fIstdout\fR\&. This will suppress normal output\&.
.sp
The option argument can be omitted\&. In that case `\fIauto\fR\*(Aq is assumed\&.
.sp
The arguments `auto\*(Aq and `none\*(Aq can be written in short form\&. Meaning only the first character is mandatory\&.
.sp
It is not valid to use \-Gp none together with \-Gx none\&.
.sp
If this option is used when entering interactive mode, it will be pre\-selected in the menu, as long the session lasts\&.
.sp
The directory the file(s) will be saved into can be modified using the
\fIcachedir\fR
variable\&.
.RE
.PP
\-Hi header\-glob:[!|<|>|<=|>=]value [\&.\&.\&.]
.RS 4
Match on integer valued entries of the `Header\*(Aq header\&. i\&.e\&. timeout\&. This option can be used multiple times\&.
.RE
.PP
\-Ht set\-type\-glob
.RS 4
Match on the set type\&.
.RE
.PP
\-Hr [!|<|>|<=|>=]value
.RS 4
Match on number of references\&. value=integer\&.
.RE
.PP
\-Hs [!|<|>|<=|>=]value
.RS 4
Match on size in memory\&. value=integer\&.
.RE
.PP
\-Hv [!|<|>|<=|>=]value
.RS 4
Match on revision number\&. value=integer\&.
.RE
.PP
\-Mc [!|<|>|<=|>=]value [\&.\&.\&.]
.RS 4
Match on the member count\&. value=integer\&.
.RE
.PP
\-Oi option\-glob:[!|<|>|<=|>=]value [\&.\&.\&.]
.RS 4
Match values of member options\&. i\&.e\&. timeout\&.
value=int | 0xhex[/0xhex] | hex:[!|<|>|<=|>=]hex\&. This option can be used multiple times\&.
.RE
.PP
\-T element [\&.\&.\&.]
.RS 4
Run
`ipset test set element`
to check if the
\fIelement\fR
is in the set\&. This option can be used multiple times\&.
.RE
.PP
\-Tm
.RS 4
Calculate the total memory usage of all matching sets\&.
.RE
.PP
\-To
.RS 4
Set timeout value (integer) in seconds for
\fBread\fR\&. This affects the listing of sets\&. The default value of the
\fIset_tmout\fR
variable, which can be set in the configuration header of the script, is 30\&. This command line option overrides it\&.
.sp
If this parameter is used when starting interactive mode, it will apply globally to all search queries performed\&. Unless you choose the
\fBTimeout\fR
option from the menu, which will overwrite the global value just for that single search\&.
.sp
To influence for how long the result is displayed in interactive mode, before returning to the main screen, set the variable
\fIiactive_tmout\fR
(default 9999999999 \- that should be sufficient time for you to stare at the result, aight?) to the desired value\&.
.RE
.PP
\-Ts
.RS 4
Count the amount of traversed sets\&.
.RE
.PP
\-Xo
.RS 4
Suppress the display of member options\&.
.RE
.PP
\-Xh header\-glob:value\-glob [\&.\&.\&.]
.RS 4
Exclude one or more [ext]glob matching header entries\&. This option can be used multiple times\&.
.RE
.PP
\-Xg pattern
.RS 4
Exclude members matching a [ext]glob pattern\&.
.RE
.PP
\-Xr pattern
.RS 4
Exclude members matching a regex pattern\&.
.RE
.PP
\-Xs pattern [\&.\&.\&.]
.RS 4
Exclude sets matching a [ext]glob pattern\&. This option can be used multiple times\&.
.RE
.PP
\-\-
.RS 4
Stop further option processing\&.
.RE
.SH "ENVIRONMENT"
.PP
The following variables are available during runtime\&. They can also be defined permanently in the configuration header of
\fBipset_list\fR, or the configuration file (ipset_list\&.conf)\&.
.PP
.PP
config_file
.RS 4
The full path to the configuration file\&. This variable is obviously only available in the configuration header, or the environment\&.
.RE
.PP
ipset
.RS 4
Ipset executable\&. The variable can be either: empty, the name of the binary, or the full path to the binary\&.
.RE
.PP
cachedir
.RS 4
Directory to save the query results into\&. The variable can be either: empty, in which case it defaults to
/var/cache/ipset_list, or a regular path\&.
.RE
.PP
set_tmout, iactive_tmout
.RS 4
See description of the `\-To\*(Aq parameter\&.
.RE
.PP
colorize
.RS 4
Colorize the output\&. The variable can be either: empty (=0), `0\*(Aq \- disabled, or `1\*(Aq \- enabled\&.
.RE
.PP
cl
.RS 4
The cl program\&. The variable can be either: empty, the name of the binary, or the full path to the binary\&. Also see description of the `\-Co\*(Aq parameter\&.
.RE
.PP
col_fg
.RS 4
Default foreground color\&. Defaults to white\&.
.RE
.PP
col_bg
.RS 4
Default background color\&. Defaults to black\&.
.RE
.PP
col_headers
.RS 4
Color for headers\&. Defaults to cyan\&.
.RE
.PP
col_members
.RS 4
Color for members\&. Defaults to yellow\&.
.RE
.PP
col_match
.RS 4
Color for matching entries\&. Defaults to red\&.
.RE
.PP
col_memsize
.RS 4
Color for displaying of memsize\&. Defaults to green\&.
.RE
.PP
col_set_count
.RS 4
Color for counting of matching sets\&. Defaults to magenta\&.
.RE
.PP
col_set_total
.RS 4
Color for counting of traversed sets\&. Defaults to blue\&.
.RE
.PP
col_highlight
.RS 4
General highlighting color\&. Defaults to white\&.
.RE
.PP
dialog_prog
.RS 4
The dialog program required for interactive mode\&. The variable can be either: empty, the name of the binary (dialog or whiptail), or the full path to the binary\&.
.RE
.PP
tput
.RS 4
The tput program \- optional for interactive mode\&. The variable can be either: empty, the name of the binary, or the full path to the binary\&.
.RE
.PP
w_height
.RS 4
Terminal window height for interactive mode\&. Best practice is to set it to 0 and let tput retrieve the value\&.
.RE
.PP
w_with
.RS 4
Terminal window with for interactive mode\&. Best practice is to set it to 0 and let tput retrieve the value\&.
.RE
.PP
l_height
.RS 4
List height for interactive mode\&. Best practice is to set it to 0 and let ipset_list calculate the value (=w_height \- 10)\&.
.RE
.SH "EXIT CODES"
.PP
An exit code of `0\*(Aq indicates success\&. A return value of `1\*(Aq is a good sign of failure\&.
.PP
If a
\fISIGNAL\fR
was received (HUP, INT, QUIT, STOP, TERM are trapped) the script exits with a return value of `111\*(Aq\&.
.SH "SEE ALSO"
.PP

\fBipset\fR(8)
\fBdialog\fR(1)
\fBwhiptail\fR(1)
\fBbash\fR(1)
\fBregex\fR(7)
.SH "AUTHOR"
.PP
\fBMart Frauenlob aka AllKind\fR <\&AllKind@fastest\&.cc\&>
.RS 4
Some guy infront of a screen\&.
.RE
.RS 4
Thanks go to the open source community\&.
.RE
